FROM ubuntu:16.04
MAINTAINER Michele Bologna <michele.bologna@gmail.com>

RUN apt-get update && \
	apt-get install -qqy wget && \
	wget -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub | apt-key add - && \
	echo "deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main" >> /etc/apt/sources.list && \
	apt-get update && \
	apt-get install -qqy salt-minion && \
    apt-get clean && \
    rm -fr /var/lib/apt/lists/*

VOLUME ["/etc/salt"]
CMD ["/usr/bin/salt-minion"]
