FROM opensuse:42.2
MAINTAINER Michele Bologna <michele.bologna@suse.com>

RUN zypper --non-interactive addrepo http://download.opensuse.org/repositories/devel:languages:python/openSUSE_Leap_42.2/devel:languages:python.repo && \
	zypper --non-interactive --no-gpg-checks refresh && \
	zypper --non-interactive in -y supervisor salt-master salt-api && \
	zypper clean && \
	useradd saltdev -p '$6$0BIlOqYqg5Rcuu5A$ojdWZ.aZztdSqPCnqsEE3ViRDcFAZ0MSp0UUvT23GG5mnbUOcalZPh8basKox2wcn4F1if2kfChOO/J1K2boe.' && \
	mkdir /var/run/supervisord/

COPY etc_master/supervisord.conf /etc/supervisor.d/supervisord.conf
COPY etc_master/salt/master /etc/salt/master
VOLUME ["/etc/salt"]
EXPOSE 8000
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor.d/supervisord.conf"]
