name: Auto Release

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  auto-release:
    uses: mbologna/.github/.github/workflows/auto-release.yml@56ec0eba66a17d43e9f4f573e9f64493b0a58895 # main
    with:
      strategy: docker
      image: docker.io/mbologna/saltstack-master
    secrets: inherit
