name: Auto Release

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  auto-release:
    uses: mbologna/.github/.github/workflows/auto-release.yml@ac1cd53e504462ed888c4101ce47813f093201df # main
    with:
      strategy: docker
      image: docker.io/mbologna/saltstack-master
    secrets: inherit
